name: GH Actions Demo
on:
  push:
    branches: [main]
    paths-ignore: [.github]
  pull_request:
    branches: [main]
  schedule:
  # every sunday at 6:15
    - cron: "15 6 * * 0"
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Triggered by
        run: echo "triggered by: ${{ github.event_name }}"
      - name: List files
        run: echo "repo files: "
        run: ls -la
      
    
    
