name: GH Actions Demo
on:
  push:
    branches: [main]
    paths-ignore: [.github]
  pull_request:
    branches: [main]
  schedule:
  # every sunday at 6:15
    - cron: "15 6 * * 0"
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          echo "triggered by event: ${{ github.event_name }}"
      - uses: actions/checkout@v3.3.0
      - name: List files in the repository
        run: |
          echo "files in repo:"
          ls -la
          
      
    
    
